### ISSUE TITLE
killerbee is not fully integrated to python3

### ISSUE THREAD

**Issue by 5l1v3r1** [AlgoSecure/iotmap#1]
python3 iotmap.py
Traceback (most recent call last):
  File "iotmap.py", line 45, in <module>
    from core.sniffing import Sniffing
  File "/media/root/WINDOWS/opt/iotmap/iotmap-master/core/sniffing.py", line 18, in <module>
    from sniffer.zigbeeSniffer import zigbeeSniffer
  File "/media/root/WINDOWS/opt/iotmap/iotmap-master/sniffer/zigbeeSniffer.py", line 23, in <module>
    from killerbee import KillerBee, PcapDumper, DLT_IEEE802_15_4
  File "/media/root/WINDOWS/opt/iotmap/lib/python3.7/site-packages/killerbee-2.7.1-py3.7-linux-x86_64.egg/killerbee/__init__.py", line 5, in <module>
    from pcapdump import *
  File "/media/root/WINDOWS/opt/iotmap/lib/python3.7/site-packages/killerbee-2.7.1-py3.7-linux-x86_64.egg/pcapdump.py", line 12
    DOT11COMMON_TAG = 000002
                           ^
SyntaxError: invalid token

killerbee is not fully integrated to python3. even after from main or other branches installation, it gives the same error. So do you know how to fix this error?

**Comment by 5l1v3r1** [comment]
ok i fixed by changing some parameters at pcapdump.py

line 12 DOT11COMMON_TAG = 0o00002
line 266 except IOError as e:

it is a killerbee issue as i repeated before but now you can run iotmap with those fixes.
